export const TIME_IDS = {
  YEAR: 0,
  MONTH_9: 1,
  MONTH_6: 2,
  MONTH_3: 3,
  MONTH_1: 4,
  WEEK2: 5,
  WEEK1: 6,
  DAY25: 7,
  DAY1: 8,
  HOUR18: 9,
  HOUR12: 10,
  HOUR_8: 11,
  HOUR_4: 12,
  HOUR2: 13,
  HOUR1: 14,
  MIN_30: 15,
  MIN10: 16,
  MIN_5: 17,
  MIN1: 18,
  SEG_30: 19
};

export const TIME_AXIS_PREFERENCES = [
  {
    // 1 year
    text: "1Y",
    totalUnit: "year",
    unit: "month",
    unitStepSize: 2,
    milliseconds: 365 * 24 * 3600 * 1000,
    optimized: true,
    diff: true,
    bins: 2000,
    id: TIME_IDS.YEAR,
  },
  {
    // 9 month
    text: "9M",
    totalUnit: "month",
    unit: "day",
    unitStepSize: 4,
    milliseconds: 9 * 30 * 24 * 3600 * 1000,
    optimized: true,
    diff: true,
    bins: 1200,
    id: TIME_IDS.MONTH_9,
  },
  {
    // 6 month
    text: "6M",
    totalUnit: "month",
    unit: "day",
    unitStepSize: 4,
    milliseconds: 6 * 30 * 24 * 3600 * 1000,
    optimized: true,
    diff: true,
    bins: 1200,
    id: TIME_IDS.MONTH_6,
  },
  {
    // 3 month
    text: "3M",
    totalUnit: "month",
    unit: "day",
    unitStepSize: 4,
    milliseconds: 3 * 30 * 24 * 3600 * 1000,
    optimized: true,
    diff: true,
    bins: 1200,
    id: TIME_IDS.MONTH_3,
  },
  {
    // 1 month
    text: "1M",
    totalUnit: "month",
    unit: "day",
    unitStepSize: 4,
    milliseconds: 30 * 24 * 3600 * 1000,
    optimized: true,
    diff: true,
    bins: 800,
    id: TIME_IDS.MONTH_1,
  },
  {
    // 2 weeks
    text: "2w",
    totalUnit: "week",
    unit: "day",
    unitStepSize: 2,
    milliseconds: 2 * 7 * 24 * 3600 * 1000,
    optimized: true,
    diff: true,
    bins: 800,
    id: TIME_IDS.WEEK2,
  },
  {
    // 1 week
    text: "1w",
    totalUnit: "week",
    unit: "day",
    unitStepSize: 2,
    milliseconds: 7 * 24 * 3600 * 1000,
    optimized: true,
    diff: true,
    bins: 800,
    id: TIME_IDS.WEEK1,
  },
  {
    // 2.5 days
    text: "2.5d",
    totalUnit: "day",
    unit: "hour",
    unitStepSize: 12,
    milliseconds: 2.5 * 24 * 3600 * 1000,
    optimized: true,
    diff: true,
    bins: 800,
    id: TIME_IDS.DAY25,
  },
  {
    // 1 day
    text: "1d",
    totalUnit: "day",
    unit: "hour",
    unitStepSize: 3,
    milliseconds: 24 * 3600 * 1000,
    optimized: true,
    diff: true,
    bins: 800,
    id: TIME_IDS.DAY1,
  },
  {
    // 18 hours
    text: "18h",
    totalUnit: "hour",
    unit: "hour",
    unitStepSize: 2,
    milliseconds: 18 * 3600 * 1000,
    optimized: true,
    diff: true,
    bins: 800,
    id: TIME_IDS.HOUR18,
  },
  {
    // 12 hours
    text: "12h",
    totalUnit: "hour",
    unit: "hour",
    unitStepSize: 2,
    milliseconds: 12 * 3600 * 1000,
    optimized: true,
    diff: true,
    bins: 800,
    id: TIME_IDS.HOUR12,
  },
  {
    // 8 hours
    text: "8h",
    totalUnit: "hour",
    unit: "hour",
    unitStepSize: 2,
    milliseconds: 8 * 3600 * 1000,
    optimized: true,
    diff: true,
    bins: 800,
    id: TIME_IDS.HOUR_8,
  },
  {
    // 4 hours
    text: "4h",
    totalUnit: "hour",
    unit: "hour",
    unitStepSize: 2,
    milliseconds: 4 * 3600 * 1000,
    optimized: true,
    diff: true,
    bins: 400,
    id: TIME_IDS.HOUR_4,
  },
  {
    // 2 hours
    text: "2h",
    totalUnit: "hour",
    unit: "minute",
    unitStepSize: 15,
    milliseconds: 2 * 3600 * 1000,
    optimized: true,
    diff: true,
    bins: 400,
    id: TIME_IDS.HOUR2,
  },
  {
    // 1 hour
    text: "1h",
    totalUnit: "hour",
    unit: "minute",
    unitStepSize: 15,
    milliseconds: 3600 * 1000,
    optimized: false,
    diff: true,
    bins: 200,
    id: TIME_IDS.HOUR1,
  },
  {
    // 30 minutes
    text: "30m",
    totalUnit: "minute",
    unit: "minute",
    unitStepSize: 3,
    milliseconds: 30 * 60 * 1000,
    optimized: false,
    diff: true,
    bins: 200,
    id: TIME_IDS.MIN_30,
  },
  {
    // 10 minutes
    text: "10m",
    totalUnit: "minute",
    unit: "minute",
    unitStepSize: 2,
    milliseconds: 10 * 60 * 1000,
    optimized: false,
    diff: true,
    bins: 50,
    id: TIME_IDS.MIN10,
  },
  {
    // 5 minutes
    text: "5m",
    totalUnit: "minute",
    unit: "second",
    unitStepSize: 30,
    milliseconds: 5 * 60 * 1000,
    optimized: false,
    diff: true,
    bins: 50,
    id: TIME_IDS.MIN_5,
  },
  {
    // 1 minute
    text: "1m",
    totalUnit: "minute",
    unit: "second",
    unitStepSize: 15,
    milliseconds: 60 * 1000,
    optimized: false,
    diff: true,
    bins: 50,
    id: TIME_IDS.MIN1,
  },
  {
    // 30 seconds
    text: "30s",
    totalUnit: "second",
    unit: "second",
    unitStepSize: 3,
    milliseconds: 30 * 1000,
    optimized: false,
    diff: true,
    bins: 50,
    id: TIME_IDS.SEG_30,
  }
];
