version: "3.8"
services:
  archiver-viewer:
    container_name: 'archiver-viewer'
    image: 'ghcr.io/lnls-sirius/archiver-viewer:${VERSION}'
    build:
      context: .
    ports:
      - 8080:80

  archiver-viewer-latest:
    container_name: 'rad-det'
    image: 'ghcr.io/lnls-sirius/rad-det-frontend'
    build:
      context: .
    ports:
      - 8080:80
